name: rag-promptflow
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==23.2.1
  - pip:
    - openai
    - azure-identity
    - azure-ai-ml
    - promptflow==0.1.0b7.post1
    - promptflow-tools
    - langchain
    - unstructured[all-docs]
    - azure-search-documents==11.4.0b9
    - pytest
    - jinja2
    - chainlit
    - tiktoken
