name: rag-promptflow
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==23.2.1
  - pip:
    - openai
    - azure-identity
    - promptflow
    - promptflow-tools
    - langchain
    - unstructured[all-docs]
    - azure-search-documents==11.4.0b9
    - dash[diskcache]
    - dash-bootstrap-components
    - dash-iconify
    - diskcache
